"""Add columns for FUTBIN data

Revision ID: 8b96202aa229
Revises: 6a52da34e598
Create Date: 2024-09-24 10:27:46.494164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b96202aa229'
down_revision: Union[str, None] = '6a52da34e598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packed_items', sa.Column('base_id', sa.String(), nullable=True))
    op.add_column('packed_items', sa.Column('resource_id', sa.String(), nullable=True))
    op.add_column('packed_items', sa.Column('league', sa.String(), nullable=True))
    op.add_column('packed_items', sa.Column('nation', sa.String(), nullable=True))
    op.add_column('packed_items', sa.Column('raretype', sa.String(), nullable=True))
    op.add_column('packed_items', sa.Column('rare', sa.String(), nullable=True))
    op.add_column('packed_items', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('player_picks', sa.Column('base_id', sa.String(), nullable=True))
    op.add_column('player_picks', sa.Column('resource_id', sa.String(), nullable=True))
    op.add_column('player_picks', sa.Column('league', sa.String(), nullable=True))
    op.add_column('player_picks', sa.Column('nation', sa.String(), nullable=True))
    op.add_column('player_picks', sa.Column('raretype', sa.String(), nullable=True))
    op.add_column('player_picks', sa.Column('rare', sa.String(), nullable=True))
    op.add_column('player_picks', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_picks', 'price')
    op.drop_column('player_picks', 'rare')
    op.drop_column('player_picks', 'raretype')
    op.drop_column('player_picks', 'nation')
    op.drop_column('player_picks', 'league')
    op.drop_column('player_picks', 'resource_id')
    op.drop_column('player_picks', 'base_id')
    op.drop_column('packed_items', 'price')
    op.drop_column('packed_items', 'rare')
    op.drop_column('packed_items', 'raretype')
    op.drop_column('packed_items', 'nation')
    op.drop_column('packed_items', 'league')
    op.drop_column('packed_items', 'resource_id')
    op.drop_column('packed_items', 'base_id')
    # ### end Alembic commands ###
