"""Add pack_value column to packs table

Revision ID: ced57c96e951
Revises: 8b96202aa229
Create Date: 2024-10-08 17:02:55.421654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ced57c96e951'
down_revision: Union[str, None] = '8b96202aa229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packs', sa.Column('pack_value', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packs', 'pack_value')
    # ### end Alembic commands ###
